# Generated by Django 4.2.6 on 2023-10-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_kyc_is_mobile_verfied'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit_card_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
