# Generated by Django 4.2.6 on 2023-10-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_account_debit_card_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='credit_card_count',
        ),
        migrations.RemoveField(
            model_name='account',
            name='debit_card_count',
        ),
    ]
