# Generated by Django 4.2.6 on 2023-10-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_account_account_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountforeign',
            name='credit_card_count',
        ),
    ]
