# Generated by Django 4.2.6 on 2023-10-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_accountforeign_credit_card_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='accountforeign',
            name='account_currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='USD', max_length=10),
        ),
    ]
