# Generated by Django 4.2.6 on 2023-10-31 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0016_alter_account_account_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountForex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('account_number', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=25, prefix='USD', unique=True)),
                ('account_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=7, max_length=25, prefix='DEX', unique=True)),
                ('pin_number', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=7, prefix='', unique=True)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('in-active', 'In-active')], default='active', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('deleted_account', models.BooleanField(default=False)),
                ('debit_card_count', models.IntegerField(blank=True, default=0, null=True)),
                ('account_currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='USD', max_length=10)),
                ('ifsc_code', models.CharField(choices=[('EPDWIN00902', 'EPDWIN00902')], default='EPDWIN00902', max_length=11)),
                ('swift_code', models.CharField(choices=[('EPDWINKL902', 'EPDWINKL902')], default='EPDWINKL902', max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='AccountForeign',
        ),
    ]
