# Generated by Django 4.2.6 on 2023-10-31 12:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0017_accountforex_delete_accountforeign'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountForex',
            new_name='AccountForeign',
        ),
    ]
