# Generated by Django 4.2.6 on 2023-11-01 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0018_rename_accountforex_accountforeign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountforeign',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account_foreign', to=settings.AUTH_USER_MODEL),
        ),
    ]
