# Generated by Django 4.2.6 on 2023-11-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_rename_accountforeign_accountforex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountforex',
            options={'ordering': ['-date'], 'verbose_name': 'Account Forex', 'verbose_name_plural': 'Forex Accounts'},
        ),
    ]
