# Generated by Django 4.2.6 on 2023-11-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_accountforex_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountforex',
            name='ifsc_code',
            field=models.CharField(choices=[('EPDW00902', 'EPDW00902')], default='EPDWIN00902', max_length=11),
        ),
    ]
