# Generated by Django 4.2.6 on 2023-11-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_account_ifsc_code_account_swift_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ifsc_code',
            field=models.CharField(choices=[('EPDW00902', 'EPDW00902')], default='EPDW00902', max_length=11),
        ),
        migrations.AlterField(
            model_name='accountforex',
            name='ifsc_code',
            field=models.CharField(choices=[('EPDW00902', 'EPDW00902')], default='EPDW00902', max_length=11),
        ),
    ]
