# Generated by Django 4.2.6 on 2023-10-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_rename_uid_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_transactions',
            field=models.IntegerField(default=0),
        ),
    ]
