# Generated by Django 4.2.6 on 2023-10-27 04:19

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_transaction_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=16, max_length=16, prefix='47'),
        ),
    ]
