# Generated by Django 4.2.6 on 2023-10-27 04:22

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_creditcard_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=14, max_length=14, prefix='47'),
        ),
    ]
