# Generated by Django 4.2.6 on 2023-10-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reciever_account_currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_account_currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=10),
        ),
    ]
