# Generated by Django 4.2.6 on 2023-11-01 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_rename_accountforex_accountforeign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_transaction_reciever_account_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='month',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='debitcard',
            name='month',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('none', 'None'), ('failed', 'Failed'), ('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('processing', 'Processing'), ('request_sent', 'Request Sent'), ('request_processing', 'Request Processing'), ('request_settled', 'Request Settled'), ('request_declined', 'Request Declined'), ('deposit_processing', 'Deposit Processing'), ('deposit_completed', 'Deposit Completed')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('none', 'None'), ('transfer', 'Transfer'), ('recieved', 'Recieved'), ('withdraw', 'Withdraw'), ('refund', 'Refund'), ('request', 'Payment Request'), ('forex_deposit', 'Forex Deposit')], default='None', max_length=100),
        ),
        migrations.CreateModel(
            name='TransactionForeign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=15, max_length=20, prefix='TRN', unique=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('reciever_account_currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=10)),
                ('sender_account_currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=10)),
                ('transaction_status', models.CharField(choices=[('none', 'None'), ('failed', 'Failed'), ('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('processing', 'Processing'), ('request_sent', 'Request Sent'), ('request_processing', 'Request Processing'), ('request_settled', 'Request Settled'), ('request_declined', 'Request Declined'), ('deposit_processing', 'Deposit Processing'), ('deposit_completed', 'Deposit Completed')], default='None', max_length=100)),
                ('transaction_type', models.CharField(choices=[('none', 'None'), ('transfer', 'Transfer'), ('recieved', 'Recieved'), ('withdraw', 'Withdraw'), ('refund', 'Refund'), ('request', 'Payment Request'), ('forex_deposit', 'Forex Deposit')], default='None', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('original_currency_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('conversion_fee', models.CharField(blank=True, default=0.0, max_length=15, null=True)),
                ('exchange_rate', models.CharField(blank=True, default=0.0, max_length=15, null=True)),
                ('amount_after_fee', models.CharField(blank=True, default=0.0, max_length=15, null=True)),
                ('easypay_rate', models.CharField(blank=True, default=0.0, max_length=15, null=True)),
                ('recipient_gets', models.CharField(blank=True, default=0.0, max_length=15, null=True)),
                ('receiver_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_account_foreign', to='account.accountforeign')),
                ('reciever', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reciever_foreign', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_foreign', to=settings.AUTH_USER_MODEL)),
                ('sender_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_account_foreign', to='account.account')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_foreign', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
