# Generated by Django 4.2.6 on 2023-11-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_creditcard_month_alter_debitcard_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionforeign',
            name='ifsc_code',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='transactionforeign',
            name='swift_code',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
