# Generated by Django 4.2.6 on 2023-11-01 12:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0021_rename_accountforeign_accountforex'),
        ('core', '0030_creditcard_card_currency_debitcard_card_currency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionForeign',
            new_name='TransactionForex',
        ),
    ]
