# Generated by Django 4.2.6 on 2023-11-01 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_accountforex_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0031_rename_transactionforeign_transactionforex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionforex',
            options={'verbose_name': 'Transaction Forex', 'verbose_name_plural': 'Forex Transactions'},
        ),
        migrations.AlterField(
            model_name='transactionforex',
            name='receiver_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_account_forex', to='account.accountforex'),
        ),
        migrations.AlterField(
            model_name='transactionforex',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reciever_forex', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionforex',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_forex', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionforex',
            name='sender_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_account_forex', to='account.account'),
        ),
        migrations.AlterField(
            model_name='transactionforex',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_forex', to=settings.AUTH_USER_MODEL),
        ),
    ]
