# Generated by Django 4.2.6 on 2023-11-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_transactionforex_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionforex',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
