# Generated by Django 4.2.6 on 2023-11-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_notification_forex_reciever_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='forex_reciever_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='forex_sender_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
